#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh
HELM="$SNAP_DATA/bin/helm3 --kubeconfig=$SNAP_DATA/credentials/client.config"
KUBECTL="$SNAP/kubectl --kubeconfig=${SNAP_DATA}/credentials/client.config"
OPENEBS_NS="openebs"

echo "Disabling OpenEBS"

disable_openebs() {

    $HELM -n $OPENEBS_NS uninstall openebs
    $KUBECTL delete namespace $OPENEBS_NS

    echo "OpenEBS disabled"
    echo "Manually clean up the directory $SNAP_COMMON/var/openebs/"
}


disable_openebs
