#!/usr/bin/env bash

set -eu

source "$SNAP/actions/common/utils.sh"

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

OPENEBS_NS="openebs"
OPENEBS_VERSION="3.3.x"
# Force to default to 3, able to override value with -j int flag
JIVA_REPLICAS=3

while getopts ":j:h:" arg
do
    case "${arg}" in
        j)
          JIVA_REPLICAS=${OPTARG}
        ;;
        h)
          usage
        ;;

    esac
done


usage() {
  #small wrapper function to call other help output functions
  print_iscsi_help

  #print function to override jiva replicas in helm command '${JIVA_REPLICAS}'
  jiva_replicas
}

print_iscsi_help() {
    echo "Make sure iscsi is installed on all nodes."
    echo "To enable iscsid: "
    echo "      sudo systemctl enable iscsid"
    echo "Please refer to the OpenEBS prerequisites (https://docs.openebs.io/docs/next/prerequisites.html)"
}

jiva_replicas(){
  echo ""
  echo ""
  echo "Default behavior is to have jiva replcas set to 3, for smaller clusters you may want to reduce"
  echo "the number of jiva replicas. To reduce the settings run the following"
  echo "microk8s enable openebs -j 2"
  echo "REPLICAS CURRENTLY SET TO: ${JIVA_REPLICAS}"
  echo ""
  echo ""
}

# Check if iscsid is installed
if ! is_strict && ! systemctl is-enabled iscsid | grep enabled &> /dev/null
  then
    echo "iscsid is not available or enabled."
    print_iscsi_help
    exit
fi

"$SNAP/microk8s-enable.wrapper" dns
"$SNAP/microk8s-enable.wrapper" helm3

# make sure the "openebs" namespace exist
$KUBECTL create namespace "$OPENEBS_NS" > /dev/null 2>&1 || true


$HELM repo add openebs https://openebs.github.io/charts
$HELM repo update
$HELM -n openebs install openebs openebs/openebs \
    --version ${OPENEBS_VERSION} \
    --set cstor.enabled=true \
    --set jiva.enabled=true \
    --set jiva.defaultPolicy.replicas=${JIVA_REPLICAS} \
    --set legacy.enabled=false \
    --set cstor.cleanup.image.tag="latest" \
    --set cstor.csiNode.kubeletDir="$SNAP_COMMON/var/lib/kubelet/" \
    --set jiva.csiNode.kubeletDir="$SNAP_COMMON/var/lib/kubelet/" \
    --set localprovisioner.basePath="$SNAP_COMMON/var/openebs/local" \
    --set ndm.sparse.path="$SNAP_COMMON/var/openebs/sparse" \
    --set varDirectoryPath.baseDir="$SNAP_COMMON/var/openebs"

echo "OpenEBS is installed"

# Help sections
echo ""
echo ""
echo "-----------------------"
echo ""
echo "When using OpenEBS with a single node MicroK8s, it is recommended to use the openebs-hostpath StorageClass"
echo "An example of creating a PersistentVolumeClaim utilizing the openebs-hostpath StorageClass"
echo ""
echo ""
echo "kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-hostpath-pvc
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
"
echo ""
echo ""
echo "-----------------------"
echo ""
echo "If you are planning to use OpenEBS with multi nodes, you can use the openebs-jiva-csi-default StorageClass."
echo "An example of creating a PersistentVolumeClaim utilizing the openebs-jiva-csi-default StorageClass"
echo ""
echo ""
echo "kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jiva-volume-claim
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
"

if is_strict
then
  print_iscsi_help
fi
