#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

KNATIVE_VERSION="1.8.2"
KUBECTL="$SNAP/microk8s-kubectl.wrapper"

echo "Disabling Knative"

if $KUBECTL get KnativeServing -n knative-serving knative-serving; then
    $KUBECTL delete KnativeServing -n knative-serving knative-serving
fi
if $KUBECTL get ns knative-serving; then
    $KUBECTL delete ns knative-serving
fi
if $KUBECTL get KnativeEventing -n knative-eventing knative-eventing; then
    $KUBECTL delete KnativeEventing -n knative-eventing knative-eventing
fi
if $KUBECTL get ns knative-eventing; then
    $KUBECTL delete ns knative-eventing
fi
if $KUBECTL get deployment knative-operator -n default; then
    $KUBECTL delete -f https://github.com/knative/operator/releases/download/knative-v$KNATIVE_VERSION/operator.yaml
fi

run_with_sudo rm -rf "${SNAP_COMMON}/plugins/kn"
run_with_sudo rm -rf "${SNAP_COMMON}/plugins/kn-admin"
run_with_sudo rm -rf "${SNAP_COMMON}/plugins/kn-event"
run_with_sudo rm -rf "${SNAP_COMMON}/plugins/kn-func"
