#!/usr/bin/env bash
set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)


NAMESPACE_PTR="easyhaproxy"

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

# Get the node name as registered in Kubernetes (lowercase, DNS-safe)
NODE_NAME=$($KUBECTL get nodes -o jsonpath='{.items[0].metadata.name}')

echo "Disabling EasyHAProxy Ingress Controller"
echo


$KUBECTL label nodes "$NODE_NAME" "easyhaproxy/node-" || true

$HELM uninstall ingress  \
    --namespace $NAMESPACE_PTR

# $KUBECTL create namespace "$NAMESPACE_PTR" > /dev/null 2>&1 || true
