#!/usr/bin/env bash
set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

echo "+=========================================+"
echo "| Enabling EasyHAProxy Ingress Controller |"
echo "+=========================================+"
echo

NODEPORTS=$($KUBECTL get svc --all-namespaces -o go-template='{{range .items}}{{range.spec.ports}}{{if .nodePort}}{{.nodePort}}{{"\n"}}{{end}}{{end}}{{end}}')
HOSTPORTS=$($KUBECTL get ds --all-namespaces -o go-template='{{range .items}}{{range .spec.template.spec.containers}}{{range .ports}}{{if .hostPort}}{{.hostPort}}{{"\n"}}{{end}}{{end}}{{end}}{{end}}')

# Get the node name as registered in Kubernetes (lowercase, DNS-safe)
NODE_NAME=$($KUBECTL get nodes -o jsonpath='{.items[0].metadata.name}')

if [ -z "$1" ]; then

    for port in $(echo $NODEPORTS $HOSTPORTS); do
        if [[ "$port" == "80" || "$port" == "443" || "$port" == "1936" ]]; then
            echo "Port $port is already in use. Please disable the ingress controller or use the --nodeport option."
            exit 1
        fi
    done
    echo "Port 80 and 443 are available. Installing as a Daemonset"

elif [ "$1" == "--nodeport" ]; then

    for port in $(echo $NODEPORTS $HOSTPORTS); do
        if [[ "$port" == "30080" || "$port" == "30443" || "$port" == "31936" ]]; then
            echo "Port $port is already in use. Please disable the component is using port $port."
            exit 1
        fi
    done
    echo "Port 30080 and 30443 are available. Installing as a Nodeport"

else

    echo 
    echo ERROR: Invalid parameter $1
    echo 
    echo "You should pass 'empty' to install as a daemonset or '--nodeport' to install as nodeport"
    echo
    exit 1

fi

"$SNAP/microk8s-enable.wrapper" dns
"$SNAP/microk8s-enable.wrapper" helm3

NAMESPACE_PTR="easyhaproxy"

$KUBECTL create namespace "$NAMESPACE_PTR" > /dev/null 2>&1 || true

$HELM repo add byjg https://opensource.byjg.com/helm > /dev/null 2>&1
$HELM repo update > /dev/null 2>&1

$KUBECTL label nodes "$NODE_NAME" "easyhaproxy/node=master" --overwrite
HELM_PACKAGE_VERSION="1.0.0"

if [ -z "$1" ]; then

    $HELM upgrade --install ingress byjg/easyhaproxy \
        --version $HELM_PACKAGE_VERSION \
        --namespace $NAMESPACE_PTR \
        --set resources.requests.cpu=100m \
        --set resources.requests.memory=128Mi \
        --set easyhaproxy.logLevel.easyhaproxy=INFO \
        --set easyhaproxy.logLevel.haproxy=INFO \
        --set easyhaproxy.logLevel.certbot=INFO

    echo
    echo "Installed as a Daemonset at port 80 and 443"
    echo

elif [ "$1" == "--nodeport" ]; then

    $HELM upgrade --install ingress byjg/easyhaproxy \
        --version $HELM_PACKAGE_VERSION \
        --namespace $NAMESPACE_PTR \
        --set resources.requests.cpu=100m \
        --set resources.requests.memory=128Mi \
        --set service.create=true \
        --set service.type=NodePort \
        --set binding.ports.http=30080 \
        --set binding.ports.https=30443 \
        --set binding.ports.stats=31936 \
        --set easyhaproxy.logLevel.easyhaproxy=INFO \
        --set easyhaproxy.logLevel.haproxy=INFO \
        --set easyhaproxy.logLevel.certbot=INFO

    echo
    echo "Installed as a Nodeport at port 30080 and 30443"
    echo

fi

