#!/usr/bin/env bash
set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

"$SNAP/microk8s-enable.wrapper" dns
"$SNAP/microk8s-enable.wrapper" helm3


NAMESPACE_PTR="easyhaproxy"

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

echo "+=========================================+"
echo "| Enabling EasyHAProxy Ingress Controller |"
echo "+=========================================+"
echo

$KUBECTL create namespace "$NAMESPACE_PTR" > /dev/null 2>&1 || true

$HELM repo add byjg https://opensource.byjg.com/helm > /dev/null 2>&1
$HELM repo update > /dev/null 2>&1

$KUBECTL label nodes $(hostname) "easyhaproxy/node=master" --overwrite

if [ -z "$1" ]; then

    $HELM upgrade --install ingress byjg/easyhaproxy \
        --namespace $NAMESPACE_PTR \
        --set resources.requests.cpu=100m \
        --set resources.requests.memory=128Mi

    echo
    echo "Installed as a Daemonset at port 80 and 443"
    echo

elif [ "$1" == "--nodeport" ]; then

    $HELM upgrade --install ingress byjg/easyhaproxy \
        --namespace $NAMESPACE_PTR \
        --set resources.requests.cpu=100m \
        --set resources.requests.memory=128Mi \
        --set service.create=true \
        --set service.type=NodePort \
        --set binding.ports.http=30080 \
        --set binding.ports.https=30443 \
        --set binding.ports.stats=31936

    echo
    echo "Installed as a Nodeport at port 30080 and 30443"
    echo

else

    echo 
    echo ERROR: Invalid parameter $1
    echo 
    echo "You should pass 'empty' to install as a daemonset or '--nodeport' to install as nodeport"
    echo

fi

