#!/usr/bin/env bash


echo "Removing kubearmor from k8s cluster"

microk8s.helm uninstall kubearmor-operator -n kubearmor

if [[ -f "$SNAP_COMMON/plugins/karmor" ]]; then
    sudo rm "$SNAP_COMMON/plugins/karmor"
fi

if [[ -f "$SNAP_COMMON/bin/karmor" ]]; then
    sudo rm "$SNAP_COMMON/bin/karmor"
fi
