#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

"$SNAP/microk8s-enable.wrapper" helm3


${SNAP}/microk8s-helm3.wrapper repo add kubearmor https://kubearmor.github.io/charts
${SNAP}/microk8s-helm3.wrapper repo update kubearmor
${SNAP}/microk8s-helm3.wrapper upgrade --install kubearmor-operator kubearmor/kubearmor-operator -n kubearmor --set autoDeploy=true --set kubearmorConfig.kubearmorImage.image=kubearmor/kubearmor:v1.2.0 --create-namespace

CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b "$SNAP_COMMON/bin"
cp "$CURRENT_DIR/karmor" "$SNAP_COMMON/plugins"
chmod +x "$SNAP_COMMON/plugins/karmor"

