#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

NAMESPACE_TRIVY="trivy-system"

TRIVY_HELM_VERSION="0.15.1"

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

do_prerequisites() {
  "$SNAP/microk8s-enable.wrapper" helm3
  # enable dns service
  "$SNAP/microk8s-enable.wrapper" dns
  # Allow some time for the apiserver to start
  sleep 5
  ${SNAP}/microk8s-status.wrapper --wait-ready --timeout 30 >/dev/null
}

VALUES=""

get_trivy() {
  # get the options
  while getopts ":f:h:" flag; do
    case "${flag}" in
            f) VALUES=${OPTARG}
              ;;
            *) echo "Usage: microk8s enable trivy"
              echo ""
              echo "With overwriting default values: microk8s enable trivy -f values.yaml"
              echo ""
              echo "See https://github.com/aquasecurity/trivy-operator/tree/main/deploy/helm for more information about the values"
              exit 0
              ;;
    esac
  done

  echo "Installing Trivy"

  if [ -n "$VALUES" ]; then
      echo "Using values file: $VALUES"
  fi

  # make sure the "trivy-system" namespace exists
  # $KUBECTL create namespace "$NAMESPACE_TRIVY" > /dev/null 2>&1 || true

  # add the trivy operator chart repository
  $HELM repo add aqua https://aquasecurity.github.io/helm-charts/

  # install the helm chart
  if [ -z "$VALUES" ]
  then
      $HELM upgrade -i trivy-operator aqua/trivy-operator \
        --namespace "$NAMESPACE_TRIVY" \
        --create-namespace \
        --set="trivy.ignoreUnfixed=true" \
        --version $TRIVY_HELM_VERSION
  else
      $HELM upgrade -i trivy-operator aqua/trivy-operator \
        --namespace "$NAMESPACE_TRIVY" \
        --create-namespace \
        --set="trivy.ignoreUnfixed=true" \
        --version $TRIVY_HELM_VERSION \
        -f $VALUES
  fi

  echo "Trivy is installed"
}

do_prerequisites
get_trivy
