#!/usr/bin/env bash

set -e

HELM="${SNAP}/microk8s-helm.wrapper"
NAMESPACE="kata-containers"

echo "Disabling kata addon"

"${HELM}" uninstall kata-deploy -n "${NAMESPACE}" "$@"

echo "Disabled kata addon"
