#!/usr/bin/env bash

set -e

HELM="${SNAP}/microk8s-helm.wrapper"
KATA_NAMESPACE="kata-containers"

echo "Disabling kata addon"

"${HELM}" uninstall kata-deploy -n "${KATA_NAMESPACE}"

echo "Disabled kata addon"
