#!/usr/bin/env bash

set -e

. "${SNAP}/actions/common/utils.sh"

debug="false"
shims="clh cloud-hypervisor dragonball fc qemu qemu-coco-dev qemu-runtime-rs qemu-sev qemu-snp qemu-tdx stratovirt qemu-nvidia-gpu qemu-nvidia-gpu-snp qemu-nvidia-gpu-tdx"
defaultShim="qemu"
createRuntimeClasses="true"
createDefaultRuntimeClass="true"
k8sDistribution="microk8s"
VERSION="3.15.0"
NAMESPACE="kata-containers"
KATA_DEPLOY_URL=https://github.com/kata-containers/kata-containers/releases/download/${VERSION}/kata-deploy-${VERSION}.tgz
HELM_OPTS=

# Enable dependencies
MICROK8S_ENABLE="${SNAP}/microk8s-enable.wrapper"
"${MICROK8S_ENABLE}" helm3

function usage {
  echo "Usage: microk8s enable kata [OPTIONS]"
  echo ""
  echo "Enable the kata addon."
  echo ""
  echo "   -h                   Print this help message"
  echo "   -n NAMESPACE         Use specified namespace (default: ${NAMESPACE})"
  echo "   -v VERSION           Kata-deploy version (default: ${VERSION})"
  echo "   --shims SHIMLIST     List of shims to install (default: \"${shims}\")"
  echo "   --defaultShim SHIM   Default shim to use with the kata RuntimeClass (default: ${defaultShim})"
}

while [ $# -ge 1 ]; do
  case $1 in
    -h|-?|--help)
      usage
      exit 0
      ;;
    -n|--namespace)
      shift
      NAMESPACE="${1}"
      shift
      ;;
    -v)
      shift
      VERSION="${1}"
      shift
      ;;
    --shims)
      shift
      shims="${1}"
      shift
      ;;
    --defaultShim)
      shift
      defaultShim="${1}"
      shift
      ;;
    *)      
      HELM_OPTS+=" ${1}"
      shift
      ;;
  esac
done

HELM="$SNAP/microk8s-helm3.wrapper"

echo "Installing kata-containers"

$HELM upgrade --install kata-deploy "${KATA_DEPLOY_URL}" \
  --create-namespace --namespace "${NAMESPACE}" \
  --set "k8sDistribution=${k8sDistribution}" \
  --set "env.debug=${debug}" \
  --set "env.shims=${shims}" \
  --set "env.defaultShim=${defaultShim}" \
  --set "env.createRuntimeClasses=${createRuntimeClasses}" \
  --set "env.createDefaultRuntimeClass=${createDefaultRuntimeClass}" \
  --wait \
  ${HELM_OPTS}

echo "================================"
echo "Enabled kata addon."
echo ""
echo ""
echo "To use the kata runtime set the 'kata' runtimeClassName, eg:"
echo ""
echo "apiVersion: v1"
echo "kind: Pod"
echo "metadata:"
echo "  name: nginx-kata"
echo "spec:"
echo "  runtimeClassName: kata"
echo "  containers:"
echo "  - name: nginx"
echo "    image: nginx"
echo ""
