#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

NAMESPACE_ARGOCD="argocd"

KUBECTL="$SNAP/kubectl --kubeconfig=${SNAP_DATA}/credentials/client.config"
HELM="$SNAP_DATA/bin/helm3 --kubeconfig=$SNAP_DATA/credentials/client.config"
KUBECTL_DELETE_ARGS="--wait=true --timeout=180s --ignore-not-found=true"

echo "Disabling ArgoCD"

$HELM delete argo-cd -n $NAMESPACE_ARGOCD

$KUBECTL delete customresourcedefinition applications.argoproj.io \
                argocdextensions.argoproj.io  \
                appprojects.argoproj.io

$KUBECTL delete $KUBECTL_DELETE_ARGS namespace "$NAMESPACE_ARGOCD" > /dev/null 2>&1 || true

echo "ArgoCD disabled"
