#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

echo "Disabling gopaddle"

#uninstall gopaddle
$HELM delete gopaddle -n gopaddle

# delete namespace
$KUBECTL delete ns gopaddle

#remove gopaddle helm folder
rm -rf "$SNAP_DATA/tmp/gopaddle"

#remove gopaddle addons
if $KUBECTL get ns gopaddle-servers >/dev/null 2>&1
then
    $KUBECTL delete ns gopaddle-servers
    
    if $KUBECTL get clusterrole gopaddle:prometheus-tool-kube-state-metrics >/dev/null 2>&1
    then
        $KUBECTL delete clusterrole gopaddle:prometheus-tool-kube-state-metrics gopaddle:prometheus-tool-server
    fi
    
    if $KUBECTL get clusterrolebinding gopaddle:event-exporter-rb >/dev/null 2>&1
    then
        $KUBECTL delete clusterrolebinding gopaddle:event-exporter-rb gopaddle:prometheus-tool-kube-state-metrics gopaddle:prometheus-tool-server
    fi
    
    if $KUBECTL get service default-http-backend >/dev/null 2>&1
    then
        $KUBECTL delete service default-http-backend
    fi
    
    if $KUBECTL get deployment default-http-backend >/dev/null 2>&1
    then
        $KUBECTL delete deployment default-http-backend
    fi
    
fi

#remove pv resourceVersion and uid
echo ""
echo "removing the resourceVersion and uid in persistentvolume"
DATA=$($KUBECTL get pv  -l gp-install-pv=microk8s-hostpath-gp-retain -o yaml| grep "name: pvc" | awk '{print $2}')

for i in $(echo $DATA | tr " " "\n")
do
    #PVNAME=$(echo $i | cut -d '"' -f 2)
    $KUBECTL patch  pv $i  --type='merge' -p '{"spec":{"claimRef":{"resourceVersion":null,"uid":null}}}'
done


# remove helm repo
$HELM repo remove gopaddle

echo "Disabled gopaddle"