#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

echo "Disabling gopaddle"

#uninstall gopaddle
$HELM delete gopaddle -n gopaddle

# delete namespace
$KUBECTL delete ns gopaddle

#remove gopaddle helm folder
rm -rf "$SNAP_DATA/tmp/gopaddle"

if $KUBECTL get clusterrole gopaddle >/dev/null 2>&1
then
    $KUBECTL delete clusterrole gopaddle
fi
    
if $KUBECTL get clusterrolebinding gopaddle >/dev/null 2>&1
then
    $KUBECTL delete clusterrolebinding gopaddle
fi

# remove helm repo
$HELM repo remove gopaddle

echo "Disabled gopaddle"
