#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
HELM_VERSION="5.0"
ARGS=$(getopt -a --options i:v:s: --longoptions "ip:,version:,storageclass:" -- "$@")
eval set -- "$ARGS"

while true; do
    case "$1" in
        -v|--version)
            HELM_VERSION="$2"
        shift 2;;
        --)
        break;;
    esac
done


do_prerequisites() {
    #refresh_opt_in_config "authentication-token-webhook" "true" kubelet
    #restart_service kubelet
    # enable helm3
    "$SNAP/microk8s-enable.wrapper" helm3
    
    # enable storage
    # "$SNAP/microk8s-enable.wrapper" hostpath-storage
    
    # enable dns
    "$SNAP/microk8s-enable.wrapper" dns
    
    # enable metrics-server
    # "$SNAP/microk8s-enable.wrapper" metrics-server
}

enable_gopaddle_lite() {
    
    echo "Enabling gopaddle"
    # download gopaddle-lite helm
    
    # add helm repo
    $HELM repo add gopaddle https://gopaddle-io.github.io/gopaddle-lite
    
    #list helm repo
    $HELM repo update
    
    if [ -z "$HELM_VERSION" ]
    then
        $HELM install gopaddle gopaddle/gopaddle --create-namespace -n gopaddle
    else
        $HELM install gopaddle gopaddle/gopaddle --create-namespace -n gopaddle --version $HELM_VERSION
    fi

}


do_prerequisites
enable_gopaddle_lite
