#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

NAMESPACE_FALCO="falco"

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"
KUBECTL_DELETE_ARGS="--wait=true --timeout=180s --ignore-not-found=true"

echo "Disabling Falco"

$HELM delete falco -n $NAMESPACE_FALCO

$KUBECTL delete $KUBECTL_DELETE_ARGS namespace "$NAMESPACE_FALCO" > /dev/null 2>&1 || true

echo "Falco disabled"
