#!/bin/bash -e
set -e

HELM="$SNAP_DATA/bin/helm3 --kubeconfig=$SNAP_DATA/credentials/client.config"
NAMESPACE="traefik"

echo "Disabling Traefik Ingress controller"

${HELM} uninstall traefik -n "${NAMESPACE}"

echo "Disabled Traefik Ingress controller"
