#!/bin/bash -e

echo "
Traefik Ingress controller is now a core addon. Enable ingress addon to deploy Traefik on your cluster:

    $ microk8s enable ingress

If you have this addon already enabled, you can disable it and start using the ingress core addon.
Note that the new ingress core addon installs Traefik in the 'ingress' namespace.
"
