#!/bin/bash -e

HELM="$SNAP_DATA/bin/helm3 --kubeconfig=$SNAP_DATA/credentials/client.config"

NAMESPACE="traefik"
TRAEFIK_CHART_VERSION="${TRAEFIK_CHART_VERSION:-20.4.0}"

echo "Enabling traefik ingress controller"
KUBECTL="$SNAP/kubectl --kubeconfig=${SNAP_DATA}/credentials/client.config"
"$SNAP/microk8s-enable.wrapper" dns
"$SNAP/microk8s-enable.wrapper" helm3
"${HELM}" repo update traefik || "${HELM}" repo add traefik https://helm.traefik.io/traefik
"${HELM}" upgrade --install --create-namespace traefik traefik/traefik -n "${NAMESPACE}" --version "${TRAEFIK_CHART_VERSION}" "$@"

echo "

Traefik Ingress controller ${TRAEFIK_CHART_VERSION} has been installed. Next, you can start
creating Ingress resources to access your services. Useful commands:

1. Get the external IP of the LoadBalancer service.


HELM="$SNAP_DATA/bin/helm3 --kubeconfig=$SNAP_DATA/credentials/client.config"

    $ microk8s kubectl get service -n traefik traefik

2. If your cluster cannot provision LoadBalancer services, you can also use the NodePort service.

    $ microk8s kubectl get service -n traefik traefik-ingress-service

3. Access the Traefik Web UI at http://localhost:18080

    $ microk8s kubectl port-forward -n traefik traefik-web-ui 18080:8080


"
