#!/usr/bin/env bash

set -e
source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
echo "Disabling Jaeger"
read -ra ARGUMENTS <<< "$1"

KUBECTL="$SNAP/kubectl --kubeconfig=${SNAP_DATA}/credentials/client.config"
MANIFESTS_PATH="${CURRENT_DIR}"
NAMESPACE="default"

if [ ! -z "${ARGUMENTS[@]}" ]
then
  NAMESPACE=${ARGUMENTS[0]}
  sed "s/namespace: default/namespace: ${NAMESPACE}/g; \
       s/default\.svc/${NAMESPACE}\.svc/g; \
       s/default\/jaeger-operator-serving-cert/${NAMESPACE}\jaeger-operator-serving-cert/g" $MANIFESTS_PATH/operator.yaml |\
       $KUBECTL delete -f -
else
  $KUBECTL delete -f "${MANIFESTS_PATH}/simplest.yaml" || true
  $KUBECTL delete -f "${MANIFESTS_PATH}/operator.yaml" || true
fi
echo "The Jaeger operator is disabled"
