#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

echo "Enabling Jaeger"

"$SNAP/microk8s-enable.wrapper" dns ingress cert-manager

read -ra ARGUMENTS <<< "$1"

MANIFESTS_PATH="${CURRENT_DIR}"
NAMESPACE="default"
KUBECTL="$SNAP/microk8s-kubectl.wrapper"

if [ ! -z "${ARGUMENTS[@]}" ]
then
  NAMESPACE=${ARGUMENTS[0]}
  $KUBECTL create ns "${NAMESPACE}" || true
  sed "s/namespace: default/namespace: ${NAMESPACE}/g; \
       s/default\.svc/${NAMESPACE}\.svc/g;\
       s/default\/jaeger-operator-serving-cert/${NAMESPACE}\/jaeger-operator-serving-cert/g" $MANIFESTS_PATH/operator.yaml |\
       $KUBECTL apply -f -
else
  $KUBECTL apply -f "${MANIFESTS_PATH}/operator.yaml"
fi

echo "Waiting for Jaeger Operator to be ready"
$KUBECTL wait pods -n "${NAMESPACE}" -l name=jaeger-operator --for condition=Ready --timeout=90s
$KUBECTL apply -f "${MANIFESTS_PATH}/simplest.yaml" 

echo "Jaeger is enabled"
