#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

VERSION=`cat ${SNAP_DATA}/../common/addons/core/addons.yaml  | grep ovn -A3 | grep version | cut -d ":" -f2- | tr -d '"' | cut -d ' ' -f2`
echo "$VERSION"
KUBECTL="$SNAP/kubectl --kubeconfig=${SNAP_DATA}/credentials/client.config"
REMOTE_PATH="https://raw.githubusercontent.com/kubeovn/kube-ovn/release-${VERSION}/dist/images/cleanup.sh"
echo "$REMOTE_PATH"
run_with_sudo mkdir -p "${SNAP_DATA}/tmp/kube-ovn"

run_with_sudo "${SNAP}/usr/bin/curl" -L ${REMOTE_PATH} -o "$SNAP_DATA/tmp/kube-ovn/cleanup.sh"

# tmp kubeconfig

run_with_sudo chmod +x "${SNAP_DATA}/tmp/kube-ovn/cleanup.sh"
run_with_sudo KUBECONFIG="${SNAP_DATA}/credentials/client.config" "${SNAP_DATA}/tmp/kube-ovn/cleanup.sh"
