#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

do_prerequisites() {
  refresh_opt_in_config "authentication-token-webhook" "true" kubelet
  restart_service kubelet
  # enable dns service
  "$SNAP/microk8s-enable.wrapper" dns
  # Allow some time for the apiserver to start
  sleep 5
  ${SNAP}/microk8s-status.wrapper --wait-ready --timeout 30 >/dev/null
}


do_prerequisites

VERSION=`cat ${SNAP_DATA}/../common/addons/core/addons.yaml
| grep ovn -A3 | grep version | cut -d ":" -f2- | tr -d '"'
| cut -d ' ' -f2` echo "$VERSION" KUBECTL="$SNAP/kubectl
--kubeconfig=${SNAP_DATA}/credentials/client.config"
REMOTE_PATH="https://raw.githubusercontent.com/kubeovn/kube-ovn/release-${VERSION}/dist/images/install.sh"
echo "$REMOTE_PATH"
run_with_sudo mkdir -p "${SNAP_DATA}/tmp/kube-ovn"

run_with_sudo "${SNAP}/usr/bin/curl" -L ${REMOTE_PATH} -o "$SNAP_DATA/tmp/kube-ovn/install.sh"

# tmp kubeconfig

run_with_sudo chmod +x "${SNAP_DATA}/tmp/kube-ovn/install.sh"
run_with_sudo KUBECONFIG="${SNAP_DATA}/credentials/client.config" "${SNAP_DATA}/tmp/kube-ovn/install.sh"
