#!/usr/bin/env bash

set -eu

source "$SNAP/actions/common/utils.sh"

BLOCK_SIZE="1000M"
KUBECTL="$SNAP/kubectl --kubeconfig=${SNAP_DATA}/credentials/client.config"
CURRENT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
if ! cat /sys/kernel/mm/transparent_hugepage/enabled | grep always &> /dev/null
then
    echo "HugePages are not available or enabled. Please make sure HugePages are enabled"
    echo "To enable HugePages:"
    echo "      echo vm.nr_hugepages = 1024 | sudo tee -a /etc/sysctl.conf"
    echo "Please restart your system after enablement."
fi

"$SNAP/microk8s-enable.wrapper" dns

# Create and mount the loopback device
run_with_sudo dd if=/dev/zero of=${SNAP_COMMON}/mayastor-disk.img bs=$BLOCK_SIZE count=10
run_with_sudo losetup -P /dev/loop666 ${SNAP_COMMON}/mayastor-disk.img
# Fetch the loop device
echo "Created local storage disk"
$KUBECTL create namespace mayastor || true
$KUBECTL apply -f https://raw.githubusercontent.com/openebs/mayastor-control-plane/master/deploy/operator-rbac.yaml
$KUBECTL apply -f https://raw.githubusercontent.com/openebs/mayastor-control-plane/master/deploy/mayastorpoolcrd.yaml
$KUBECTL apply -f https://raw.githubusercontent.com/openebs/mayastor/master/deploy/nats-deployment.yaml
$KUBECTL apply -f https://raw.githubusercontent.com/openebs/mayastor/develop/deploy/etcd/storage/localpv.yaml

# Using our sts without affinity
$KUBECTL apply -f "${CURRENT_DIR}/etcd.yaml"

$KUBECTL apply -f https://raw.githubusercontent.com/openebs/mayastor/master/deploy/etcd/svc.yaml
$KUBECTL apply -f https://raw.githubusercontent.com/openebs/mayastor/master/deploy/etcd/svc-headless.yaml
$KUBECTL apply -f https://raw.githubusercontent.com/openebs/mayastor/master/deploy/csi-daemonset.yaml
$KUBECTL apply -f https://raw.githubusercontent.com/openebs/mayastor-control-plane/master/deploy/core-agents-deployment.yaml
$KUBECTL apply -f https://raw.githubusercontent.com/openebs/mayastor-control-plane/master/deploy/rest-deployment.yaml
$KUBECTL apply -f https://raw.githubusercontent.com/openebs/mayastor-control-plane/master/deploy/rest-service.yaml
$KUBECTL apply -f https://raw.githubusercontent.com/openebs/mayastor-control-plane/master/deploy/csi-deployment.yaml
$KUBECTL apply -f https://raw.githubusercontent.com/openebs/mayastor-control-plane/master/deploy/msp-deployment.yaml
$KUBECTL apply -f https://raw.githubusercontent.com/openebs/mayastor/master/deploy/mayastor-daemonset.yaml

$KUBECTL scale --replicas=1 sts/nats -n mayastor


echo "Mayastor is installed"
echo "" 
echo "" 
echo "-----------------------"
echo "" 
echo "Next steps require a MayastorPool that uses the device you just created."
echo "" 
echo "" 
echo "kind: MayastorPool
apiVersion: v1
metadata:
  name: microk8s-control-plane-pool
  namespace:mayastor
spec:
  name: $HOSTNAME
  disks: ['/dev/loop666']
"
