#!/usr/bin/env bash

set -e

HELM="${SNAP}/microk8s-helm.wrapper"
MICROK8S_CONFIG="${SNAP}/microk8s-config.wrapper"

NAMESPACE="microcks"
MICROCKS_CHART_VERSION="1.7.1"
IP=`"${MICROK8S_CONFIG}" | grep "server: https:" | sed "s/\/\// /" | awk -F ':' '{print $3}' | sed "s/ //"`

echo "Enabling Microcks"

"${HELM}" repo add microcks https://microcks.io/helm
"${HELM}" upgrade --install --create-namespace microcks microcks/microcks -n "${NAMESPACE}" --version "${MICROCKS_CHART_VERSION}" --set microcks.url=microcks."${IP}".nip.io --set keycloak.url=keycloak."${IP}".nip.io

echo "

Microcks ${MICROCKS_CHART_VERSION} has been installed and enabled.
Happy API(s) Mocking and Testing -> https://microcks."${IP}".nip.io 

Getting started -> https://microcks.io/documentation/getting-started/

Useful commands:

1. Get the external IP of the Microcks service:

    $ microk8s kubectl get service -n microcks microcks

2. Access the Microcks Web UI on a different port (default is 8080): 

    $ microk8s kubectl port-forward -n microcks microcks 18080:8080

3. Retrieve all Microcks' URLs of the created ingress:

    $ microk8s kubectl get ingress -n microcks

"
