#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

echo "Disabling osm-edge"
${SNAP}/microk8s-status.wrapper --wait-ready --timeout 30 >/dev/null

echo "Removing osm-edge control plane"
KUBECONFIG=$SNAP_DATA/credentials/client.config $SNAP_DATA/bin/osm uninstall mesh -f
echo "Deleting osm-edge binary."
run_with_sudo rm -f "${SNAP_COMMON}/plugins/osm"
run_with_sudo rm -f "$SNAP_DATA/bin/osm"
