#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

echo "Enabling Helm 3"

if [ ! -f "${SNAP_DATA}/bin/helm3" ]
then
  SOURCE_URI="https://get.helm.sh"
  HELM_VERSION="v3.5.0"

  echo "Fetching helm version ${HELM_VERSION}."
  mkdir -p "/tmp/helm3"
  (cd "/tmp/helm3"
  curl -L "${SOURCE_URI}/helm-${HELM_VERSION}-linux-${SNAP_ARCH}.tar.gz" -o "/tmp/helm3/helm.tar.gz"
  tar -xzf "/tmp/helm3/helm.tar.gz" || true)

  mkdir -p "$SNAP_DATA/bin/"
  mv "/tmp/helm3/linux-${SNAP_ARCH}/helm" "${SNAP_DATA}/bin/helm3"
  chmod +x "${SNAP_DATA}/bin/"
  chmod +x "${SNAP_DATA}/bin/helm3"

  rm -rf "/tmp/helm3"
fi

echo "Helm 3 is enabled"
