#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

KUBECTL="$SNAP/microk8s-kubectl.wrapper"

echo "Disabling Istio"

run_with_sudo "${SNAP_DATA}/bin/istioctl" -c "${SNAP_DATA}/credentials/client.config" uninstall --purge -y
run_with_sudo "${KUBECTL}" delete namespace istio-system > /dev/null 2>&1 || true

run_with_sudo rm -rf "${SNAP_DATA}/bin/istioctl"
run_with_sudo rm -rf "$SNAP_USER_COMMON/istio-auth.lock"
run_with_sudo rm -rf "$SNAP_USER_COMMON/istio.lock"

echo "Istio is terminating"
