#!/usr/bin/env bash

set -e

NAMESPACE_KWASM="kwasm-system"
OPERATOR_VERSION="0.2.2"
INSTALLER_VERSION="v0.3.0"

"$SNAP/microk8s-enable.wrapper" helm3
HELM="$SNAP/microk8s-helm3.wrapper"

echo "Installing KWasm"

$HELM repo add --force-update kwasm http://kwasm.sh/kwasm-operator/ 
$HELM upgrade -i -n $NAMESPACE_KWASM --create-namespace kwasm-operator kwasm/kwasm-operator \
    --version $OPERATOR_VERSION \
    --set kwasmOperator.installerImage="ghcr.io/kwasm/kwasm-node-installer:$INSTALLER_VERSION" \
    --set kwasmOperator.autoProvision="true"

echo "KWasm is installed with the following versions:"
echo "  kwasm-operator: $OPERATOR_VERSION"
echo "  kwasm-node-installer: $INSTALLER_VERSION"
echo ""
echo "If you need help to get started visit:"
echo "    https://kwasm.sh/?dist=microk8s#Quickstart"