#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

KUBECTL="$SNAP/microk8s-kubectl.wrapper"

do_prerequisites() {
  # enable dns service
  "$SNAP/microk8s-enable.wrapper" dns
  ${SNAP}/microk8s-status.wrapper --wait-ready --timeout 30 >/dev/null
  run_with_sudo mkdir -p "${SNAP_DATA}/keda"
}


get_keda () {
  KEDA_VERSION="v2.12.0"
  KEDA_ERSION=$(echo $KEDA_VERSION | sed 's/v//g')
  echo "Fetching keda version $KEDA_ERSION."
  fetch_as https://github.com/kedacore/keda/releases/download/${KEDA_VERSION}/keda-${KEDA_ERSION}.yaml "$SNAP_DATA/keda/keda.yaml"
}


enable_keda() {
  echo "Enabling KEDA"
  $KUBECTL apply --server-side -f "${SNAP_DATA}/keda/keda.yaml"
}

do_prerequisites
get_keda
enable_keda

echo "The KEDA is enabled."
