#!/bin/bash -e

HELM="${SNAP}/microk8s-helm.wrapper"
VERSION=0.19.0

POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    --namespace)
      NAMESPACE="$2"
      shift # past argument
      shift # past value
      ;;
    --authtoken)
      NGROK_AUTHTOKEN="$2"
      shift # past argument
      shift # past value
      ;;
    --api-key)
      NGROK_API_KEY="$2"
      shift # past argument
      shift # past value
      ;;
    --secret-name)
      SECRET_NAME="$2"
      shift # past argument
      shift # past value
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

if [ -z "$NAMESPACE" ]; then
  echo "Namespace (--namespace) was not specified. Defaulting to ngrok-operator namespace."
  NAMESPACE="ngrok-operator"
fi

if [ -z "$SECRET_NAME" ]; then
  if [ -z "$NGROK_AUTHTOKEN" ] || [ -z "$NGROK_API_KEY" ]; then
    echo "Either --secret-name or both --authtoken and --api-key must be specified. Please see https://ngrok.com/docs/getting-started/kubernetes/ingress/ for more information."
    exit 1
  fi
fi

echo "Enabling ngrok Kubernetes operator in ${NAMESPACE} namespace"

"${HELM}" repo update ngrok || "${HELM}" repo add ngrok https://charts.ngrok.com

if [ -n "$SECRET_NAME" ]; then
  "${HELM}" upgrade --install --create-namespace ngrok-operator ngrok/ngrok-operator --namespace "${NAMESPACE}" --set credentials.secret.name="${SECRET_NAME}" --version=${VERSION}
else
  "${HELM}" upgrade --install --create-namespace ngrok-operator ngrok/ngrok-operator --namespace "${NAMESPACE}" --set credentials.apiKey="${NGROK_API_KEY}" --set credentials.authtoken="${NGROK_AUTHTOKEN}" --version=${VERSION}
fi

echo "---"
echo ""
echo "The ngrok Kubernetes operator has been successfully installed in the ${NAMESPACE} namespace."
echo ""

if [ -n "$SECRET_NAME" ]; then
    echo "You specified a secret named ${SECRET_NAME}. Please ensure that secret exists in your cluster with the keys 'API_KEY' and 'AUTHTOKEN'."
    echo "For help creating the secret, see: https://ngrok.com/docs/getting-started/kubernetes/ingress/"
    echo ""
fi

echo "Now you can create Ingress resources with 'ingressClassName: ngrok' to expose your services through ngrok."
echo "If you have the Gateway API CRDs installed, you can use those with ngrok too. See https://ngrok.com/docs/getting-started/kubernetes/gateway-api/ for examples."
echo "For the getting-started guide, see: https://ngrok.com/docs/getting-started/kubernetes/ingress/"
