#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

NAMESPACE_STARBOARD="starboard-system"

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"
KUBECTL_DELETE_ARGS="--wait=true --timeout=180s --ignore-not-found=true"

echo "Disabling Starboard"

$HELM delete starboard-operator -n $NAMESPACE_STARBOARD

$KUBECTL delete $KUBECTL_DELETE_ARGS namespace "$NAMESPACE_STARBOARD" > /dev/null 2>&1 || true

echo "Starboard disabled"
