#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

NAMESPACE_STARBOARD="starboard-system"

STARBOARD_HELM_VERSION="0.10.0"

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"

do_prerequisites() {
  "$SNAP/microk8s-enable.wrapper" helm3
  # enable dns service
  "$SNAP/microk8s-enable.wrapper" dns
  # Allow some time for the apiserver to start
  sleep 5
  ${SNAP}/microk8s-status.wrapper --wait-ready --timeout 30 >/dev/null
}

VALUES=""

get_starboard() {
  # get the options
  while getopts ":f:h:" flag; do
    case "${flag}" in
            f) VALUES=${OPTARG}
              ;;
            *) echo "Usage: microk8s enable starboard"
              echo ""
              echo "With overwriting default values: microk8s enable starboard -f values.yaml"
              echo ""
              echo "See https://github.com/aquasecurity/starboard/tree/main/deploy/helm for more information about the values"
              exit 0
              ;;
    esac
  done

  echo "Installing Starboard"

  if [ -n "$VALUES" ]; then
      echo "Using values file: $VALUES"
  fi

  # make sure the "starboard-system" namespace exists
  # $KUBECTL create namespace "$NAMESPACE_STARBOARD" > /dev/null 2>&1 || true

  # add the Starboard chart repository
  $HELM repo add aqua https://aquasecurity.github.io/helm-charts/

  # install the helm chart
  if [ -z "$VALUES" ]
  then
      $HELM upgrade -i starboard-operator aqua/starboard-operator \
        --namespace "$NAMESPACE_STARBOARD" \
        --create-namespace \
        --set="trivy.ignoreUnfixed=true" \
        --version $STARBOARD_HELM_VERSION
  else
      $HELM upgrade -i starboard-operator aqua/starboard-operator \
        --namespace "$NAMESPACE_STARBOARD" \
        --create-namespace \
        --set="trivy.ignoreUnfixed=true" \
        --version $STARBOARD_HELM_VERSION \
        -f $VALUES
  fi

  echo "Starboard is installed"
}

do_prerequisites
get_starboard
